import { FaJs } from "react-icons/fa";
import { DiReact } from "react-icons/di";
import { TbBrandNextjs } from "react-icons/tb";
import { SiTailwindcss, SiTypescript, SiPrisma } from "react-icons/si";

export const ItemDate = [
  {
    id: 1,
    src: "/31SaaS.png",
    link: "https://31-saa-s.vercel.app/",
    title: "31SaaS",
    text: "printed fierce avoid nature question action car pig nor record after brick gun sudden take run between airplane sheep softly doubt choice sum effort pound dinner worry tongue",
    gitLink: "https://github.com/ramyus889/31SaaS",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 2,
    src: "/LessonEng.png",
    link: "https://lesson-english2-two.vercel.app/",
    title: "Lesson English",
    text: "constantly tide globe no trip act hard hold depth seven late herself torn peace teacher rocket bush doubt win magic recall through yes forty",
    gitLink: "https://github.com/ramyus889/LessonEnglish2",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 3,
    src: "/mirrorWorld.png",
    link: "https://mirror-world-seven.vercel.app/",
    title: "Mirror World",
    text: "bill porch being concerned more sell on baby swung moment body herd load circus mighty smooth upward better shadow then became bound development took",
    gitLink: "https://github.com/ramyus889/MirrorWorld",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 4,
    src: "/portfolio.png",
    link: "https://personalwebfrontend.vercel.app/",
    title: "Portfolio",
    text: "throughout double health near upward continued leave find apartment part sink fourth handle flies traffic therefore army former dinner plan answer ruler safe blind",
    gitLink: "https://github.com/ramyus889/portfolio",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 5,
    src: "/next-pizza.png",
    link: "https://next-js-pizza-sigma.vercel.app/",
    title: "Next Pizza",
    text: "bill wear composition respect library declared music public plane notice therefore design buy worry sit express understanding pet effort whispered forty carbon dust no",
    gitLink: "https://github.com/ramyus889/Next.js-Pizza",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
      {
        id: 6,
        language: "Prisma",
        link: "https://www.prisma.io/",
        icon: <SiPrisma color="#007ACC" size={18} />,
      },
    ],
  },
];
