import { FaJs } from "react-icons/fa";
import { DiReact } from "react-icons/di";
import { TbBrandNextjs } from "react-icons/tb";
import { SiTailwindcss, SiTypescript, SiPrisma } from "react-icons/si";

export const ItemDate = [
  {
    id: 1,
    src: "/31SaaS.png",
    link: "https://31-saa-s.vercel.app/",
    title: "31SaaS",
    date: "2024-03-14 - 2024-08-15",
    gitLink: "https://github.com/ramyus889/31SaaS",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        colSpan: "",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        colSpan: "",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        colSpan: "",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 2,
    src: "/LessonEng.png",
    link: "https://lesson-english2-two.vercel.app/",
    title: "Lesson English",
    date: "2024-04-04 - 2024-07-10",
    gitLink: "https://github.com/ramyus889/LessonEnglish2",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        colSpan: "",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        colSpan: "",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        colSpan: "",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 3,
    src: "/mirrorWorld.png",
    link: "https://mirror-world-seven.vercel.app/",
    title: "Mirror World",
    date: "2024-05-23 - 2024-08-15",
    gitLink: "https://github.com/ramyus889/MirrorWorld",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        colSpan: "",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        colSpan: "",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        colSpan: "",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 4,
    src: "/portfolio.png",
    link: "https://personalwebfrontend.vercel.app/",
    title: "Portfolio",
    date: "2024-06-19 - 2024-07-10",
    gitLink: "https://github.com/ramyus889/portfolio",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        colSpan: "",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        colSpan: "",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        colSpan: "",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "min-[480px]:col-span-2",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "max-[480px]:col-span-2",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
    ],
  },
  {
    id: 5,
    src: "/next-pizza.png",
    link: "https://next-js-pizza-sigma.vercel.app/",
    title: "Next Pizza",
    date: "2024-07-25 - 2024-08-01",
    gitLink: "https://github.com/ramyus889/Next.js-Pizza",
    languageContent: [
      {
        id: 1,
        language: "Next.js",
        colSpan: "",
        link: "https://nextjs.org/",
        icon: <TbBrandNextjs color="#ffffff" size={23} />,
      },
      {
        id: 2,
        language: "React.js",
        colSpan: "",
        link: "https://react.dev/",
        icon: <DiReact color="#61DAFB" size={23} />,
      },
      {
        id: 3,
        language: "TailwindCSS",
        colSpan: "",
        link: "https://tailwindcss.com/",
        icon: <SiTailwindcss color="#38B2AC" size={23} />,
      },
      {
        id: 4,
        language: "TypeScript",
        colSpan: "",
        link: "https://www.typescriptlang.org/",
        icon: <SiTypescript color="#007ACC" size={18} />,
      },
      {
        id: 5,
        language: "JavaScript",
        colSpan: "",
        link: "https://www.javascript.com/",
        icon: <FaJs color="#F7DF1E" size={18} />,
      },
      {
        id: 6,
        language: "Prisma",
        colSpan: "",
        link: "https://www.prisma.io/",
        icon: <SiPrisma color="#007ACC" size={18} />,
      },
    ],
  },
];
